### ISSUE TITLE
rerun SQL on a different backend

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis-birdbrain#53]
this is purely for demo purposes, but needed -- fill out the `bot.execute_last_sql()` method, taking in a connection and blindly running `con.sql()` with the last SQL attachment generated by the bot

this would be useful motivation for better attachment methods for retreiving attachments

**Comment by jitingxu1** [comment]
resolved by https://github.com/ibis-project/ibis-birdbrain/pull/58
