### ISSUE TITLE
transpile sql between dialects

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis-birdbrain#54]
implement the `bot.transpile_sql` (currently called `translate_sql`, recommend renaming) method likely just using SQLGlot directly

takes a SQL string as input. along w/ #53, good motivation for better attachment methods (get last SQL Attachment, get a SQL attachment by some input text, etc.)

**Comment by jitingxu1** [comment]
was resolved by https://github.com/ibis-project/ibis-birdbrain/pull/58
