### ISSUE TITLE
table attachments formatted incorrectly

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/ibis-birdbrain#56]
doesn't really matter functionally, but TableAttachments aren't formatted correct -- the `**table**` is too far right:

<img width="784" alt="image" src="https://github.com/ibis-project/ibis-birdbrain/assets/54814569/2f623f1e-5c72-40dc-91ba-6aa6d369edfc">

**Comment by jitingxu1** [comment]
Hi @lostmygithubaccount , how do you want to format the table attachment?

**Comment by lostmygithubaccount** [comment]
the `**table**` part is just indented too far to the right, not a big deal but annoying
